import { createFileRoute } from "@tanstack/react-router"
import { PageHero } from "@/components/PageHero"
import { getCommittee } from "@/lib/cms/server"
export const Route = createFileRoute("/about")({ loader: () => getCommittee(), head: () => ({ meta: [{ title: "About | BrightFutures Greenwich" }, { name: "description", content: "Why BrightFutures exists and what the student-led Greenwich society stands for." }, { property: "og:title", content: "About | BrightFutures Greenwich" }] }), component: AboutPage })
const objectives = ["Give care-experienced and estranged students a place to meet and support each other.", "Make it easier for students to raise issues and help shape life at Greenwich.", "Run social activities and share useful workshops, information and opportunities."]
function AboutPage() { const committee = Route.useLoaderData(); return <div>
 <PageHero eyebrow="Why BrightFutures exists" title="A society shaped by the students in it." body="BrightFutures is a student-led community for care-experienced and estranged students at Greenwich. It exists because university is better when there are people around who get it."/>
 <section className="bg-cream px-6 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><h2 className="font-display text-4xl text-forest">What we do</h2><div className="space-y-6 text-lg leading-relaxed text-forest/70"><p>We make room for friendships, events, projects and ideas that students actually want. You can come along occasionally, stay connected or help run things.</p><p>We also speak up. Students can raise issues together, share what is and isn’t working and push for practical change at Greenwich.</p></div></div></section>
 <section className="bg-cream-dim px-6 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-coral">Our objectives</p><ol className="mt-8 border-t border-forest/25">{objectives.map((body, i) => <li key={body} className="grid gap-4 border-b border-forest/20 py-7 sm:grid-cols-[5rem_1fr]"><span className="font-display text-3xl text-coral">0{i+1}</span><p className="max-w-3xl text-lg leading-relaxed text-forest/75">{body}</p></li>)}</ol></div></section>
 <section className="bg-forest px-6 py-20 text-cream sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><p className="text-xs font-bold uppercase tracking-[.18em] text-coral-light">Student-led</p><div><h2 className="font-display text-4xl sm:text-5xl">Students make the decisions.</h2><p className="mt-6 leading-relaxed text-cream/75">BrightFutures is a University of Greenwich student society operating through Greenwich Students’ Union. We work with GSU, Greenwich Cares and university staff when it helps, but we are not a University department.</p></div></div></section>
 <section className="bg-cream px-6 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-green">Meet the committee</p><h2 className="mt-4 font-display text-4xl text-forest">The students running BrightFutures</h2><ol className="mt-10 grid border-t border-forest/25 lg:grid-cols-3">{committee.map((person, i) => <li key={person.name} className={`border-b border-forest/20 py-8 lg:min-h-64 lg:px-8 ${i > 0 ? "lg:border-l" : "lg:pl-0"}`}><p className="font-display text-2xl text-coral">0{i+1}</p>{person.photo ? <img src={person.photo} alt="" className="mt-8 aspect-[4/5] w-full object-cover" /> : null}<h3 className="mt-10 font-display text-3xl uppercase text-forest">{person.name}</h3><p className="mt-3 max-w-xs leading-relaxed text-forest/65">{person.role}</p></li>)}</ol></div></section>
 </div> }
