import { createFileRoute, Link, Outlet, useRouterState } from "@tanstack/react-router"
import { ArrowRight } from "lucide-react"
import { ArtWallCard } from "@/components/art-wall/ArtWallCard"
import { ArtWallGallery } from "@/components/art-wall/ArtWallGallery"
import { PageHero } from "@/components/PageHero"
import { artWallPrompt, type ArtWallSubmission } from "@/data/art-wall"
import { getArtWall } from "@/lib/cms/server"
export const Route = createFileRoute("/art-wall")({ loader: (): Promise<ArtWallSubmission[]> => getArtWall(), head: () => ({ meta: [{ title: "Art Wall | BrightFutures Greenwich" }, { name: "description", content: "Explore art, photography, poetry and creative work shared by the BrightFutures Greenwich community." }] }), component: ArtWallRoute })
function ArtWallRoute() { const childRoute = useRouterState({ select: (s) => s.matches.some((m) => m.routeId === "/art-wall/$slug" || m.routeId === "/art-wall/submit") }); return childRoute ? <Outlet /> : <ArtWallPage /> }
function ArtWallPage() {
  const works = Route.useLoaderData()
  const featured = works.filter((work) => work.featured)
  return <div>
    <PageHero eyebrow="The BrightFutures Art Wall" title="Creativity, in our own words." body="Art, poetry, photography and creative work shared by the BrightFutures community." visual={<div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-coral">A community exhibition</p><p className="mt-4 font-display text-4xl leading-none">Made here.<br /><em className="font-normal text-coral">Shared here.</em></p><p className="mt-6 text-sm leading-relaxed text-forest/70">Everything on the wall has been shared by a member of our community and reviewed before being published.</p></div>} />
    <section className="border-b border-forest/15 bg-cream px-6 py-6 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-sm leading-relaxed text-forest/70">The wall is a calm place to share something you have made, without likes, rankings or pressure.</p><div className="flex flex-wrap gap-3"><Link to="/art-wall/submit" className="inline-flex min-h-11 items-center bg-coral px-5 font-bold text-cream">Add something to the wall</Link><a href="#on-the-wall" className="inline-flex min-h-11 items-center border border-forest/30 px-5 font-bold text-forest">Explore the wall</a></div></div></section>
    {artWallPrompt.active ? <section className="bg-cream-dim px-6 py-12 sm:px-8"><div className="mx-auto grid max-w-7xl gap-5 border-l-4 border-coral pl-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="text-xs font-extrabold tracking-[.16em] text-coral">THIS MONTH’S PROMPT</p><h2 className="mt-2 font-display text-4xl text-forest">{artWallPrompt.title}</h2><p className="mt-2 text-forest/70">{artWallPrompt.description}</p></div><Link to="/art-wall/submit" className="inline-flex min-h-11 items-center gap-2 font-bold text-forest underline decoration-coral decoration-2 underline-offset-4">Respond to the prompt <ArrowRight size={17}/></Link></div></section> : null}
    {featured.length ? <section className="bg-paper px-6 py-16 sm:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-extrabold tracking-[.16em] text-coral">SELECTED BY THE COMMITTEE</p><h2 className="mt-2 font-display text-5xl text-forest">Featured on the wall</h2><div className="mt-9 grid gap-7 md:grid-cols-2">{featured.slice(0, 2).map((work, index) => <ArtWallCard key={work.slug} work={work} index={index}/>)}</div></div></section> : null}
    <section id="on-the-wall" className="bg-cream px-6 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6 border-b-2 border-forest pb-6"><div><p className="text-xs font-extrabold tracking-[.16em] text-coral">THE EXHIBITION</p><h2 className="mt-2 font-display text-5xl text-forest sm:text-6xl">On the wall</h2></div><Link to="/art-wall/submit" className="font-bold text-forest underline decoration-coral decoration-2 underline-offset-4">Got something to add?</Link></div>{works.length ? <div className="mt-9"><ArtWallGallery works={works}/></div> : <div className="mt-10 max-w-2xl border-l-4 border-coral bg-paper p-8"><h2 className="font-display text-4xl text-forest">The wall is waiting for its first pieces.</h2><p className="mt-4 leading-relaxed text-forest/70">Draw something. Write something. Photograph something. Share something that matters to you.</p><Link to="/art-wall/submit" className="mt-6 inline-flex bg-forest px-5 py-3 font-bold text-cream">Be the first to add something</Link></div>}</div></section>
  </div>
}
