import { createFileRoute, Link } from "@tanstack/react-router"
import { PageHero } from "@/components/PageHero"

export const Route = createFileRoute("/community-guidelines")({
  head: () => ({ meta: [{ title: "Community Guidelines | BrightFutures HQ" }, { name: "description", content: "Guidelines for participating in BrightFutures HQ community features." }] }),
  component: GuidelinesPage,
})

function GuidelinesPage() {
  return <div><PageHero title="Community Guidelines" body="Last updated: 11 August 2026" /><article className="bg-cream px-6 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-3xl space-y-10 leading-relaxed text-forest/75"><div className="space-y-3"><p>BrightFutures HQ exists to provide an independent, welcoming digital space supporting BrightFutures Society and its wider community.</p><p>BrightFutures HQ is a project of <strong>Vibes in Care CIC</strong>. It works independently in support of the Society and is not a University of Greenwich or Greenwich Students&apos; Union service.</p><p>These guidelines apply when interacting with BrightFutures HQ, submitting content or taking part in community features.</p></div>
    <Section title="Be respectful"><p>People in this community will have different backgrounds, experiences and perspectives.</p><p>Disagreement is okay. Personal attacks, intimidation, targeted harassment, bullying or deliberately humiliating another person are not.</p></Section>
    <Section title="Protect people’s privacy"><p>Do not post another person&apos;s private information without their permission.</p><p>This is particularly important when discussing experiences involving care, estrangement, accommodation, family relationships, health, education or support services.</p><p>You do not need to explain or prove your personal circumstances in order to participate in BrightFutures HQ.</p><p>Please think carefully before sharing sensitive information about yourself through free-text forms.</p></Section>
    <Section title="Your story belongs to you"><p>People should have control over whether and how their experiences are shared.</p><p>A private Community Check-In is private unless you make a separate choice to propose specific content for publication.</p><p>Where public sharing is available, BrightFutures HQ will ask you to identify the exact excerpt that may be considered for publication and how you would like to be identified.</p><p>Publication remains subject to editorial review.</p></Section>
    <Section title="Do not speak for someone else"><p>You can discuss issues affecting the community, but do not present another person&apos;s experience as your own or publicly identify somebody else&apos;s personal circumstances without permission.</p><p>Where possible, discuss wider issues without including information that could unnecessarily identify another person.</p></Section>
    <Section title="Challenge ideas, not people"><p>BrightFutures should be a place where people can raise difficult issues, including criticism of services, institutions and systems.</p><p>You are welcome to disagree with decisions, policies and ideas.</p><p>Keep criticism focused on the issue rather than attacking, threatening or targeting individuals.</p></Section>
    <Section title="No discrimination or hate"><p>Content attacking or degrading people because of protected or personal characteristics is not welcome.</p><p>This includes racist, sexist, homophobic, transphobic, ableist or otherwise discriminatory abuse.</p></Section>
    <Section title="Keep people safe"><p>Do not use BrightFutures HQ to threaten violence, encourage serious harm, exploit another person or deliberately place somebody at risk.</p><p>BrightFutures HQ is not an emergency or crisis-response service.</p><p>Community Check-Ins are reviewed as community engagement rather than continuously monitored safeguarding reports.</p><p>If something submitted through the platform raises an exceptional and immediate safety concern, the team may need to take proportionate action where legally justified.</p></Section>
    <Section title="Keep submissions genuine"><p>Community features exist to help us understand and support the community.</p><p>Do not deliberately manipulate submissions, impersonate other people, spam forms or repeatedly submit false information intended to disrupt the service.</p></Section>
    <Section title="Public contributions may be moderated"><p>Submitting something for possible publication does not guarantee that it will appear publicly.</p><p>BrightFutures HQ may decline, edit or remove public material where necessary to:</p><ul className="mt-3 list-disc space-y-2 pl-6"><li>protect someone&apos;s privacy or safety;</li><li>comply with the law;</li><li>prevent harassment or discrimination;</li><li>maintain the purpose of the community;</li><li>correct materially misleading information;</li><li>respect another person&apos;s rights; or</li><li>maintain appropriate editorial standards.</li></ul><p>Where practical, minor editorial changes will preserve the contributor&apos;s intended meaning.</p></Section>
    <Section title="Raising concerns"><p>If you believe something published through BrightFutures HQ breaches these Guidelines, affects your privacy or should be reviewed, contact the BrightFutures HQ team through the website&apos;s <Link to="/contact" className="font-semibold text-forest underline">contact page</Link>.</p><p>Concerns will be considered by an authorised member of the team and appropriate action taken where necessary.</p></Section>
    <Section title="Our relationship with BrightFutures Society"><p>BrightFutures HQ exists to support BrightFutures Society and its community, but the two should not be confused.</p><p>BrightFutures Society remains an official Students&apos; Union-affiliated society.</p><p>BrightFutures HQ is the independent platform supporting that community and is operated as a project of Vibes in Care CIC.</p><p>These Guidelines govern participation in <strong>BrightFutures HQ</strong>. They do not replace any rules, codes of conduct or procedures that apply separately to membership of BrightFutures Society through Greenwich Students&apos; Union.</p></Section>
  </div></article></div>
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="font-display text-2xl text-forest">{title}</h2>{children}</section> }
