import { createFileRoute, Link } from "@tanstack/react-router"
import { PageHero } from "@/components/PageHero"
import { getSettings } from "@/lib/cms/server"
export const Route = createFileRoute("/get-involved")({ loader: () => getSettings(), head: () => ({ meta: [{ title: "Get Involved | BrightFutures Greenwich" }, { name: "description", content: "Join BrightFutures, take part in events or help shape the society." }, { property: "og:title", content: "Get Involved | BrightFutures Greenwich" }] }), component: GetInvolvedPage })
const routeItems = (membershipUrl: string) => [{ title: "Join as a member", body: "Membership is free for 2026/27 and takes a couple of minutes. It’s the easiest way to hear what’s happening.", cta: "Become a member", href: membershipUrl }, { title: "Take part", body: "Come to events, projects and activities.", cta: "See what’s on", to: "/events" }, { title: "Help shape it", body: "Suggest an idea, volunteer or ask about the committee.", cta: "Talk to us", to: "/contact" }] as const
function GetInvolvedPage() { const routes = routeItems(Route.useLoaderData().membership_url); return <div><PageHero eyebrow="Get involved" title="Come along in whatever way works for you." body="Membership is free. Come to one event, join a project or help run the society. There’s no expected level of involvement."/>
 <section className="bg-cream px-6 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="grid border-t border-forest/25 lg:grid-cols-3">{routes.map((r, i) => <article key={r.title} className={`border-b border-forest/20 py-9 lg:px-8 ${i === 0 ? "lg:pl-0" : "lg:border-l"}`}><p className="text-xs font-bold uppercase tracking-[.18em] text-coral">0{i+1}</p><h2 className="mt-6 font-display text-4xl text-forest">{r.title}</h2><p className="mt-4 min-h-14 leading-relaxed text-forest/70">{r.body}</p>{"href" in r ? <a href={r.href} className="mt-7 inline-flex border-b border-forest pb-1 font-semibold text-forest hover:text-coral">{r.cta} →</a> : <Link to={r.to} className="mt-7 inline-flex border-b border-forest pb-1 font-semibold text-forest hover:text-coral">{r.cta} →</Link>}</article>)}</div>
 <div className="mt-14 flex flex-wrap gap-x-8 gap-y-3 border-t border-forest/15 pt-7 text-sm">{["Volunteering", "Committee", "Collaboration", "Event ideas"].map(item => <Link key={item} to="/contact" className="font-semibold text-forest/65 hover:text-forest">{item} →</Link>)}</div>
 <div className="mt-20 grid gap-8 bg-forest px-7 py-10 text-cream sm:px-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><h2 className="font-display text-3xl">Questions, ideas or offers to help?</h2><p className="mt-3 text-cream/70">Send a message straight to the student committee.</p></div><Link to="/contact" className="border border-cream/30 px-6 py-3 text-center font-semibold">Contact us</Link></div></div></section></div> }
