import { createFileRoute, Link } from "@tanstack/react-router"
import { PageHero } from "@/components/PageHero"

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms of Service | BrightFutures HQ" }, { name: "description", content: "Terms for accessing and using BrightFutures HQ." }] }),
  component: TermsPage,
})

const rules = ["misuse, disrupt or interfere with the website;", "attempt to gain unauthorised access to restricted systems or information;", "submit malicious software or code;", "impersonate another person;", "use the service to harass, threaten or abuse someone;", "knowingly submit materially false or misleading information for a harmful purpose;", "use automated systems to overwhelm, scrape or abuse the service; or", "use BrightFutures HQ for unlawful activity."]

function TermsPage() {
  return <div><PageHero title="Terms of Service" body="Last updated: 11 August 2026" /><article className="bg-cream px-6 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-3xl space-y-10 leading-relaxed text-forest/75"><p>These Terms apply when you access or use BrightFutures HQ.</p>
    <Section title="1. About BrightFutures HQ"><p>BrightFutures HQ is an independent community platform supporting BrightFutures Society and its community.</p><p>BrightFutures HQ is a project operated by <strong>Vibes in Care CIC</strong>.</p><p>BrightFutures HQ is not a service of the University of Greenwich or Greenwich Students&apos; Union.</p><p>BrightFutures Society remains a separate Students&apos; Union-affiliated society. Use of BrightFutures HQ does not constitute official membership of BrightFutures Society, and joining the Society through Greenwich Students&apos; Union does not automatically create a relationship with BrightFutures HQ.</p></Section>
    <Section title="2. Using the service"><p>You may use BrightFutures HQ to access community information, discover activities and resources, submit ideas, contact the team, participate in Community Check-Ins and use other features we make available.</p><p>You agree to use the service lawfully and in accordance with these Terms and our <Link to="/community-guidelines" className="font-semibold text-forest underline">Community Guidelines</Link>.</p><p>You must not deliberately:</p><ul className="mt-3 list-disc space-y-2 pl-6">{rules.map(rule => <li key={rule}>{rule}</li>)}</ul></Section>
    <Section title="3. Community Check-Ins"><p>The Community Check-In is intended as a voluntary community reflection and engagement tool.</p><p>It is <strong>not</strong> an emergency service, safeguarding reporting system, counselling service, mental-health service or substitute for professional support.</p><p>You decide what you wish to share. Please avoid providing unnecessary personal or sensitive information.</p><p>Submitting a private Check-In does not make its contents public.</p><p>Where we offer an option to propose an excerpt for publication, that content remains subject to consent and editorial review.</p></Section>
    <Section title="4. Public contributions"><p>Where you submit material for possible publication, you retain ownership of your original content.</p><p>You give Vibes in Care CIC permission, through BrightFutures HQ, to store, review and, where you have specifically agreed to publication, display the approved content through the channels covered by your consent.</p><p>We may edit formatting, spelling or presentation where this does not materially change your meaning. We will not intentionally turn private Check-In responses into public content without the appropriate publication choice and review.</p><p>We may decide not to publish submitted material and may remove published material where reasonably necessary.</p></Section>
    <Section title="5. Community standards"><p>Participation in BrightFutures HQ is subject to our Community Guidelines.</p><p>We may moderate, reject or remove material that breaches those Guidelines, presents a safety or legal concern, infringes another person&apos;s rights or is otherwise inappropriate for the service.</p></Section>
    <Section title="6. Availability"><p>We aim to keep BrightFutures HQ reliable and available, but we cannot guarantee uninterrupted or error-free access.</p><p>We may modify, suspend or withdraw features where reasonably necessary for maintenance, security, legal compliance or development of the service.</p></Section>
    <Section title="7. External services and links"><p>BrightFutures HQ may link to websites and services operated by other organisations, including the University of Greenwich, Greenwich Students&apos; Union and social-media platforms.</p><p>Those services are independently operated and have their own terms and privacy practices.</p><p>A link does not necessarily mean that BrightFutures HQ or Vibes in Care CIC endorses everything provided by that service.</p></Section>
    <Section title="8. Privacy"><p>Personal information is handled in accordance with the BrightFutures HQ <Link to="/privacy" className="font-semibold text-forest underline">Privacy Policy</Link>.</p><p>Vibes in Care CIC is the data controller for personal information processed through BrightFutures HQ where stated in that policy.</p></Section>
    <Section title="9. Intellectual property"><p>Unless otherwise stated, the BrightFutures HQ website, its original design, branding, written material and other original platform content are owned by or licensed to Vibes in Care CIC.</p><p>Content belonging to BrightFutures Society, the University of Greenwich, Greenwich Students&apos; Union, individual contributors or other third parties remains the property of its respective owner.</p><p>Nothing in these Terms transfers ownership of your original contributions to Vibes in Care CIC.</p></Section>
    <Section title="10. Our responsibilities"><p>We will take reasonable steps to operate BrightFutures HQ responsibly and securely.</p><p>Information and resources provided through the platform are generally intended for community and informational purposes. They should not be treated as professional legal, medical, financial or other regulated advice unless expressly stated otherwise.</p><p>Nothing in these Terms excludes or limits liability where doing so would be unlawful.</p></Section>
    <Section title="11. Ending or restricting access"><p>We may restrict access to parts of the service where reasonably necessary to protect users, maintain security, enforce these Terms or Community Guidelines, or comply with legal obligations.</p><p>Serious or repeated misuse may result in access being restricted.</p></Section>
    <Section title="12. Changes to these Terms"><p>We may update these Terms when BrightFutures HQ changes or where legal or operational requirements make an update necessary.</p><p>The latest version will be published on the website with its revision date.</p><p>Material changes affecting how the service operates may also be communicated through the website where appropriate.</p></Section>
    <Section title="13. Contact"><p>Questions about these Terms or BrightFutures HQ can be submitted through the website&apos;s <Link to="/contact" className="font-semibold text-forest underline">contact page</Link>.</p><p>BrightFutures HQ is a project of <strong>Vibes in Care CIC</strong> and operates as an independent platform supporting BrightFutures Society and its community.</p></Section>
  </div></article></div>
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="font-display text-2xl text-forest">{title}</h2>{children}</section> }
