import { api, field, select } from "./lib.mjs"

const collections = {
  events: { fields: [field("title", "string", { is_nullable: false }), field("slug", "string", { is_nullable: false, is_unique: true }), select("status", ["draft", "provisional", "confirmed", "cancelled", "completed"], "draft"), field("academic_year", "string"), select("category", ["social", "coffee-connect", "community", "opportunity", "voice-advocacy", "wellbeing", "trips", "seasonal"]), field("start_date", "timestamp", { is_nullable: false }), field("end_date", "timestamp"), field("time_display", "string"), field("location", "string"), field("description", "text"), field("body", "text", {}, { interface: "input-rich-text-html" }), field("registration_url", "string"), field("featured", "boolean", { default_value: false }), field("cover_image", "uuid", {}, { interface: "file-image", special: ["file"] }), field("cover_image_alt", "string"), field("accessibility_info", "text"), field("published_at", "timestamp"), field("sort", "integer")], icon: "event" },
  posts: { fields: [field("title", "string", { is_nullable: false }), field("slug", "string", { is_nullable: false, is_unique: true }), select("status", ["draft", "review", "published", "archived"], "draft"), field("excerpt", "text"), field("body", "text", {}, { interface: "input-rich-text-html" }), field("featured_image", "uuid", {}, { interface: "file-image", special: ["file"] }), field("featured_image_alt", "string"), field("author_name", "string"), select("category", ["news", "society", "student-voice", "opportunities", "events"]), field("published_at", "timestamp"), field("featured", "boolean", { default_value: false }), field("seo_title", "string"), field("seo_description", "text")], icon: "article" },
  committee: { fields: [field("name", "string", { is_nullable: false }), field("role", "string", { is_nullable: false }), field("role_short", "string"), field("bio", "text"), field("photo", "uuid", {}, { interface: "file-image", special: ["file"] }), field("photo_alt", "string"), field("email", "string"), field("display_order", "integer"), field("active", "boolean", { default_value: true }), field("academic_year", "string")], icon: "groups" },
  resources: { fields: [field("title", "string", { is_nullable: false }), field("description", "text"), select("category", ["greenwich-support", "accommodation", "money", "wellbeing", "careers", "opportunities", "community"]), field("organisation", "string"), field("url", "string"), field("featured", "boolean", { default_value: false }), field("display_order", "integer"), select("status", ["draft", "published", "archived"], "draft")], icon: "book" },
  site_settings: { singleton: true, fields: [field("site_name", "string"), field("tagline", "text"), field("membership_url", "string"), field("instagram_url", "string"), field("contact_email", "string"), field("homepage_announcement", "text"), field("homepage_announcement_url", "string"), field("show_announcement", "boolean", { default_value: false }), field("default_seo_title", "string"), field("default_seo_description", "text")], icon: "settings" },
  contact_messages: { fields: [field("name", "string", { is_nullable: false }), field("email", "string", { is_nullable: false }), field("subject", "string", { is_nullable: false }), field("message", "text", { is_nullable: false }), select("status", ["new", "read", "replied", "closed"], "new"), field("source_page", "string"), field("ip_hash", "string"), field("user_agent", "text"), field("date_created", "timestamp", {}, { special: ["date-created"], readonly: true })], icon: "mail", hidden: true },
  ideas: { fields: [field("idea", "text", { is_nullable: false }), field("name", "string"), field("email", "string"), select("status", ["new", "reviewing", "planned", "done", "not-proceeding"], "new"), field("internal_notes", "text", {}, { note: "Admin-only. Exclude this field from non-administrator editor permissions." }), field("date_created", "timestamp", {}, { special: ["date-created"], readonly: true })], icon: "lightbulb" },
}
collections.events.fields.push(field("date_created", "timestamp", {}, { special: ["date-created"], readonly: true }), field("date_updated", "timestamp", {}, { special: ["date-updated"], readonly: true }), field("user_created", "uuid", {}, { special: ["user-created"], readonly: true }), field("user_updated", "uuid", {}, { special: ["user-updated"], readonly: true }))
collections.posts.fields.push(field("date_created", "timestamp", {}, { special: ["date-created"], readonly: true }), field("date_updated", "timestamp", {}, { special: ["date-updated"], readonly: true }))
for (const [name, definition] of Object.entries(collections)) {
  const existing = await api(`/collections/${name}`).catch(() => null)
  if (!existing) await api("/collections", { method: "POST", body: JSON.stringify({ collection: name, meta: { icon: definition.icon, singleton: !!definition.singleton, hidden: !!definition.hidden }, schema: {} }) })
  else await api(`/collections/${name}`, { method: "PATCH", body: JSON.stringify({ meta: { icon: definition.icon, singleton: !!definition.singleton, hidden: !!definition.hidden } }) })
  const current = await api(`/fields/${name}`)
  for (const spec of definition.fields) { const present = current.some(item => item.field === spec.field); if (present) await api(`/fields/${name}/${spec.field}`, { method: "PATCH", body: JSON.stringify({ meta: spec.meta, schema: spec.schema }) }); else await api(`/fields/${name}`, { method: "POST", body: JSON.stringify(spec) }) }
}

const publicRules = [
  ["events", "read", { _or: [{ status: { _eq: "confirmed" } }, { status: { _eq: "completed" } }, { status: { _eq: "cancelled" } }] }],
  ["posts", "read", { _and: [{ status: { _eq: "published" } }, { published_at: { _lte: "$NOW" } }] }],
  ["committee", "read", { active: { _eq: true } }], ["resources", "read", { status: { _eq: "published" } }], ["site_settings", "read", {}],
]
const permissions = await api("/permissions?limit=-1")
const publicPolicy = (await api("/policies?filter[name][_eq]=Public&limit=1").catch(() => []))[0]?.id ?? null
for (const [collection, action, rule] of publicRules) { const existing = permissions.find(p => p.collection === collection && p.action === action && p.policy === publicPolicy); const payload = { collection, action, policy: publicPolicy, permissions: rule, validation: {}, presets: {}, fields: ["*"] }; if (existing) await api(`/permissions/${existing.id}`, { method: "PATCH", body: JSON.stringify(payload) }); else await api("/permissions", { method: "POST", body: JSON.stringify(payload) }) }
for (const collection of ["ideas", "contact_messages"]) { for (const action of ["read", "create", "update", "delete"]) { const existing = permissions.find(p => p.collection === collection && p.action === action && p.policy === publicPolicy); if (existing) await api(`/permissions/${existing.id}`, { method: "DELETE" }) } }
console.log("Directus schema and least-privilege public read permissions are configured.")
