/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/events'
    | '/get-involved'
    | '/privacy'
    | '/resources'
    | '/stories'
    | '/events/$slug'
    | '/stories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/events'
    | '/get-involved'
    | '/privacy'
    | '/resources'
    | '/stories'
    | '/events/$slug'
    | '/stories/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/events'
    | '/get-involved'
    | '/privacy'
    | '/resources'
    | '/stories'
    | '/events/$slug'
    | '/stories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GetInvolvedRoute: typeof GetInvolvedRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GetInvolvedRoute: GetInvolvedRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  StoriesRoute: StoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
