/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as PartnershipsPerksRouteImport } from './routes/partnerships_.perks'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const PartnershipsPerksRoute = PartnershipsPerksRouteImport.update({
  id: '/partnerships_/perks',
  path: '/partnerships/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/check-in': typeof CheckInRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/highlights': typeof HighlightsRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/voice': typeof VoiceRoute
  '/events/$slug': typeof EventsSlugRoute
  '/partnerships/perks': typeof PartnershipsPerksRoute
  '/stories/$slug': typeof StoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/check-in': typeof CheckInRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/highlights': typeof HighlightsRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/voice': typeof VoiceRoute
  '/events/$slug': typeof EventsSlugRoute
  '/partnerships/perks': typeof PartnershipsPerksRoute
  '/stories/$slug': typeof StoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/check-in': typeof CheckInRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/highlights': typeof HighlightsRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/terms': typeof TermsRoute
  '/voice': typeof VoiceRoute
  '/events/$slug': typeof EventsSlugRoute
  '/partnerships_/perks': typeof PartnershipsPerksRoute
  '/stories/$slug': typeof StoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/check-in'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/events'
    | '/get-involved'
    | '/highlights'
    | '/partnerships'
    | '/privacy'
    | '/resources'
    | '/stories'
    | '/terms'
    | '/voice'
    | '/events/$slug'
    | '/partnerships/perks'
    | '/stories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/check-in'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/events'
    | '/get-involved'
    | '/highlights'
    | '/partnerships'
    | '/privacy'
    | '/resources'
    | '/stories'
    | '/terms'
    | '/voice'
    | '/events/$slug'
    | '/partnerships/perks'
    | '/stories/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/check-in'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/events'
    | '/get-involved'
    | '/highlights'
    | '/partnerships'
    | '/privacy'
    | '/resources'
    | '/stories'
    | '/terms'
    | '/voice'
    | '/events/$slug'
    | '/partnerships_/perks'
    | '/stories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CheckInRoute: typeof CheckInRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EventsRoute: typeof EventsRouteWithChildren
  GetInvolvedRoute: typeof GetInvolvedRoute
  HighlightsRoute: typeof HighlightsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  TermsRoute: typeof TermsRoute
  VoiceRoute: typeof VoiceRoute
  PartnershipsPerksRoute: typeof PartnershipsPerksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/partnerships_/perks': {
      id: '/partnerships_/perks'
      path: '/partnerships/perks'
      fullPath: '/partnerships/perks'
      preLoaderRoute: typeof PartnershipsPerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
  }
}

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CheckInRoute: CheckInRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EventsRoute: EventsRouteWithChildren,
  GetInvolvedRoute: GetInvolvedRoute,
  HighlightsRoute: HighlightsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  StoriesRoute: StoriesRouteWithChildren,
  TermsRoute: TermsRoute,
  VoiceRoute: VoiceRoute,
  PartnershipsPerksRoute: PartnershipsPerksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
